#!/bin/sh
# Download optional external skills into a gitignored directory.
#
# Run from anywhere:
#
#     ./scripts/setup-protocols.sh
#
# The coordinator can resolve installed protocols from the catalogs this writes.
# Nothing here is imported by the coordinator, and the published skills stay
# usable when these downloads are absent. Repeat runs fast-forward clean
# checkouts; user data is never deleted or hard-reset.

set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd -P)
DEST="$ROOT/.external"

MATT_URL=${MATT_SKILLS_URL:-https://github.com/mattpocock/skills.git}
MATT_DIR="$DEST/mattpocock-skills"
MATT_CATALOG="$MATT_DIR/skills"

PLUGINS_URL=${CURSOR_PLUGINS_URL:-https://github.com/cursor/plugins.git}
PLUGINS_DIR="$DEST/cursor-plugins"
# SKILL.md files live at pstack/skills in cursor/plugins.
PSTACK_SPARSE="pstack/skills"
PSTACK_CATALOG="$PLUGINS_DIR/pstack/skills"

CATALOG_ENV="$DEST/catalog.env"

run() {
  printf '+ %s\n' "$*"
  "$@"
}

refuse() {
  printf 'Refusing setup: %s\n' "$*" >&2
  exit 1
}

# Git records relative local clone sources with the physical caller directory
# prepended. Use that same spelling for clone and repeat-run origin validation.
# Leave absolute paths and Git URLs unchanged.
local_source_url() {
  case "$1" in
    /*) printf '%s\n' "$1" ;;
    *)
      if [ -d "$1" ]; then
        printf '%s/%s\n' "$(pwd -P)" "$1"
      else
        printf '%s\n' "$1"
      fi
      ;;
  esac
}

# Check both destinations before changing either working tree. Existing
# directories are accepted only as clean, ordinary clones of the expected URL.
preflight_clone() {
  url=$1
  dest=$2
  [ ! -L "$dest" ] || refuse "symlink destination: $dest"
  if [ ! -e "$dest" ]; then
    return 0
  fi
  [ -d "$dest/.git" ] && [ ! -L "$dest/.git" ] ||
    refuse "occupied destination is not an ordinary Git clone: $dest"
  [ "$(git -C "$dest" rev-parse --show-toplevel)" = "$dest" ] ||
    refuse "destination is not its own Git working tree: $dest"
  [ "$(git -C "$dest" config --get remote.origin.url)" = "$url" ] ||
    refuse "origin URL differs from the expected source: $dest"
  status=$(git -C "$dest" status --porcelain --untracked-files=all --ignored) ||
    refuse "cannot inspect local changes in $dest"
  [ -z "$status" ] ||
    refuse "local changes, untracked or ignored files in $dest; preserve or move them before retrying"
  branch=$(git -C "$dest" symbolic-ref --quiet --short HEAD) ||
    refuse "detached HEAD in $dest"
  [ "$(git -C "$dest" config --get "branch.$branch.remote")" = origin ] ||
    refuse "branch does not track origin: $dest"
  ref=$(git -C "$dest" config --get "branch.$branch.merge") ||
    refuse "branch has no upstream: $dest"
  case "$ref" in
    refs/heads/*) ;;
    *) refuse "unsupported upstream ref in $dest" ;;
  esac
}

# Fetches may change Git metadata, but no working tree is updated until every
# existing clone can advance without discarding local commits.
prepare_update() {
  dest=$1
  if [ -d "$dest/.git" ]; then
    branch=$(git -C "$dest" symbolic-ref --quiet --short HEAD)
    ref=$(git -C "$dest" config --get "branch.$branch.merge")
    run git -C "$dest" fetch origin "$ref"
    git -C "$dest" merge-base --is-ancestor HEAD FETCH_HEAD ||
      refuse "local commits or rewritten upstream in $dest; only fast-forward updates are allowed"
  fi
}

ensure_clone() {
  url=$1
  dest=$2
  sparse=$3
  if [ -d "$dest/.git" ]; then
    run git -C "$dest" merge --ff-only FETCH_HEAD
    if [ -n "$sparse" ]; then
      run git -C "$dest" sparse-checkout set "$sparse"
    fi
    return
  fi
  if [ -n "$sparse" ]; then
    run git clone --depth 1 --filter=blob:none --sparse "$url" "$dest"
    run git -C "$dest" sparse-checkout set "$sparse"
  else
    run git clone --depth 1 "$url" "$dest"
  fi
}

if ! command -v git >/dev/null 2>&1; then
  echo "git is required" >&2
  exit 1
fi

# The Coordinator separates catalogs with ':', so those paths cannot be
# represented. Newlines are rejected to keep the generated shell file simple.
case "$ROOT" in
  *:*|*'
'*) refuse "repository path contains a colon or newline: $ROOT" ;;
esac
[ ! -L "$DEST" ] || refuse "symlink destination: $DEST"
if [ -e "$DEST" ] && [ ! -d "$DEST" ]; then
  refuse "occupied destination is not a directory: $DEST"
fi

# Double-quote shell metacharacters, including dollars/backticks/backslashes.
# Treat an existing catalog as user content unless it is our exact generated
# output (or the exact legacy output for this repository).
value="$PSTACK_CATALOG:$MATT_CATALOG"
quoted=$(printf '%s' "$value" | sed 's/[\\`"$]/\\&/g')
catalog=$(printf '# Generated by scripts/setup-protocols.sh; do not edit.\nexport COORDINATOR_PROTOCOL_CATALOG="%s"\n' "$quoted")
[ ! -L "$CATALOG_ENV" ] || refuse "symlink catalog: $CATALOG_ENV"
if [ -e "$CATALOG_ENV" ]; then
  [ -f "$CATALOG_ENV" ] || refuse "occupied catalog is not a regular file: $CATALOG_ENV"
  existing=$(cat "$CATALOG_ENV")
  legacy="export COORDINATOR_PROTOCOL_CATALOG=$value"
  [ "$existing" = "$catalog" ] || [ "$existing" = "$legacy" ] ||
    refuse "catalog contains unrelated content or local edits: $CATALOG_ENV; preserve or move it before retrying"
fi

PLUGINS_URL=$(local_source_url "$PLUGINS_URL")
MATT_URL=$(local_source_url "$MATT_URL")
preflight_clone "$PLUGINS_URL" "$PLUGINS_DIR"
preflight_clone "$MATT_URL" "$MATT_DIR"
prepare_update "$PLUGINS_DIR"
prepare_update "$MATT_DIR"
mkdir -p "$DEST"
ensure_clone "$PLUGINS_URL" "$PLUGINS_DIR" "$PSTACK_SPARSE"
ensure_clone "$MATT_URL" "$MATT_DIR" ""

missing=0
for path in "$PSTACK_CATALOG" "$MATT_CATALOG"; do
  if [ ! -d "$path" ]; then
    if [ "$missing" -eq 0 ]; then
      echo "expected catalog directory was not created:" >&2
    fi
    printf '  %s\n' "$path" >&2
    missing=1
  fi
done
if [ "$missing" -ne 0 ]; then
  exit 1
fi

# pstack first: its skill names are the protocols the coordinator looks up.
printf '%s\n' "$catalog" > "$CATALOG_ENV"

printf '\n'
echo "Downloaded skills are in:"
printf '  %s\n' "$PSTACK_CATALOG" "$MATT_CATALOG"
printf 'Catalog list written to %s\n' "$CATALOG_ENV"
printf 'COORDINATOR_PROTOCOL_CATALOG=%s\n' "$value"
